import { db } from "../server/db";
import { roadmaps, roadmapSteps } from "../shared/schema";

// ─── NEW ROADMAPS (IDs 139–150) ────────────────────────────────────────────
// Priority: letscode.co.in first, then roadmap.sh — no duplicates with existing 101-138

const NEW_ROADMAPS = [
  // ═══════════════════════════════════════════════════════════════
  // 139. iOS DEVELOPMENT
  // ═══════════════════════════════════════════════════════════════
  {
    title: "iOS Development",
    description: "Build native iOS apps with Swift and SwiftUI — from Xcode setup to App Store submission. Master Apple's modern frameworks and deliver polished, performant iPhone and iPad apps.",
    category: "Mobile",
    icon: "Apple",
    steps: [
      { section: "Swift Fundamentals", order: 1, title: "Swift Language Basics", description: "Learn Swift's type system, constants vs variables (let/var), all primitive types, string interpolation, optionals (?), optional chaining, nil-coalescing (??), and forced unwrapping. Understand how Swift differs from other languages with its safety-first design.", resources: [{ title: "Swift Official Documentation", url: "https://docs.swift.org/swift-book/" }, { title: "100 Days of Swift (Hacking with Swift)", url: "https://www.hackingwithswift.com/100" }] },
      { section: "Swift Fundamentals", order: 2, title: "Swift Control Flow, Collections & Functions", description: "Master if/guard/switch/while/for-in control flow. Work with arrays, dictionaries, sets, and tuples. Write functions with labeled parameters, default values, variadic parameters, inout parameters, and closures (trailing closure syntax, capturing values).", resources: [{ title: "Swift — Collection Types (docs)", url: "https://docs.swift.org/swift-book/documentation/the-swift-programming-language/collectiontypes/" }, { title: "Hacking with Swift — Swift in 60 Seconds", url: "https://www.hackingwithswift.com/sixty" }] },
      { section: "Swift Fundamentals", order: 3, title: "Swift OOP — Classes, Structs & Protocols", description: "Understand the value (struct/enum) vs reference (class) distinction, inheritance, method overriding, initializers, deinit, computed properties, property observers (willSet/didSet), protocols and protocol-oriented programming, extensions, and generics.", resources: [{ title: "Swift Protocols Deep Dive (objc.io)", url: "https://www.objc.io/books/advanced-swift/" }, { title: "Point-Free — Swift Functional Programming", url: "https://www.pointfree.co" }] },
      { section: "Swift Fundamentals", order: 4, title: "Swift Concurrency — async/await & Actors", description: "Write modern concurrent Swift with async/await, Task, TaskGroup, async let, structured concurrency, and actors for data-race safety. Understand the Swift concurrency model, MainActor, and how to bridge to completion-handler APIs with continuations.", resources: [{ title: "Swift Concurrency Manifesto (Swift Forums)", url: "https://gist.github.com/lattner/31ed37682ef1576b16bca1432ea9f782" }, { title: "WWDC 2021 — Meet async/await in Swift", url: "https://developer.apple.com/videos/play/wwdc2021/10132/" }] },
      { section: "Xcode & UIKit", order: 5, title: "Xcode IDE & Project Structure", description: "Navigate Xcode confidently: project navigator, scheme/target/build settings, Interface Builder, Simulator management, Instruments for profiling, and the Swift Package Manager integration. Set up signing, capabilities, and Info.plist.", resources: [{ title: "Apple Developer — Xcode Overview", url: "https://developer.apple.com/xcode/" }, { title: "Kodeco (Ray Wenderlich) — Xcode Essentials", url: "https://www.kodeco.com/ios/paths/learn" }] },
      { section: "Xcode & UIKit", order: 6, title: "UIKit Fundamentals", description: "Build UIs programmatically and with Storyboards: UIViewController lifecycle (viewDidLoad, viewWillAppear, etc.), UIView hierarchy, Auto Layout constraints (NSLayoutConstraint, visual format, anchors), UITableView/UICollectionView with diffable data sources.", resources: [{ title: "Apple — Human Interface Guidelines", url: "https://developer.apple.com/design/human-interface-guidelines/" }, { title: "Hacking with Swift — UIKit", url: "https://www.hackingwithswift.com/read" }] },
      { section: "SwiftUI", order: 7, title: "SwiftUI Fundamentals", description: "Build declarative UIs with SwiftUI: View protocol, basic views (Text, Image, Button, Toggle, Slider, TextField), layout containers (HStack, VStack, ZStack, Grid, LazyVGrid/LazyHGrid), modifiers as composable transformations, and the @ViewBuilder pattern.", resources: [{ title: "Apple — SwiftUI Tutorials", url: "https://developer.apple.com/tutorials/swiftui" }, { title: "100 Days of SwiftUI (Hacking with Swift)", url: "https://www.hackingwithswift.com/100/swiftui" }] },
      { section: "SwiftUI", order: 8, title: "SwiftUI State & Data Flow", description: "Master SwiftUI's state management: @State for local state, @Binding for two-way parent-child data, @StateObject/@ObservedObject with ObservableObject+@Published, @EnvironmentObject for dependency injection, and the new @Observable macro (iOS 17+).", resources: [{ title: "WWDC 2023 — Discover Observation in SwiftUI", url: "https://developer.apple.com/videos/play/wwdc2023/10149/" }, { title: "SwiftUI Lab (advanced patterns)", url: "https://swiftui-lab.com" }] },
      { section: "SwiftUI", order: 9, title: "SwiftUI Navigation & Animations", description: "Implement navigation with NavigationStack and NavigationPath (iOS 16+), sheets, fullScreenCover, popover, alerts, and tab views. Add animations with .animation(), withAnimation, matched geometry effects, transitions, and custom Animatable shapes.", resources: [{ title: "WWDC 2022 — The SwiftUI cookbook for navigation", url: "https://developer.apple.com/videos/play/wwdc2022/10054/" }, { title: "Kavsoft — SwiftUI Animations (YouTube)", url: "https://www.youtube.com/@Kavsoft" }] },
      { section: "Data & Networking", order: 10, title: "Networking with URLSession", description: "Fetch data with URLSession: URLRequest configuration, async/await API (data(from:), upload, download), JSON decoding with Codable (JSONDecoder/JSONEncoder), error handling, background URL sessions, and authentication (URLCredential, token injection).", resources: [{ title: "Apple — URLSession Documentation", url: "https://developer.apple.com/documentation/foundation/urlsession" }, { title: "Hacking with Swift — URLSession Networking", url: "https://www.hackingwithswift.com/books/ios-swiftui/downloading-data-from-the-internet" }] },
      { section: "Data & Networking", order: 11, title: "Core Data & SwiftData", description: "Persist data locally with Core Data (NSManagedObjectContext, NSFetchRequest, NSPersistentContainer, relationships, migrations) and the modern SwiftData framework (@Model, @Query, ModelContainer). Implement iCloud sync with CloudKit.", resources: [{ title: "Apple — Core Data Documentation", url: "https://developer.apple.com/documentation/coredata" }, { title: "WWDC 2023 — Model your schema with SwiftData", url: "https://developer.apple.com/videos/play/wwdc2023/10195/" }] },
      { section: "Advanced iOS", order: 12, title: "Push Notifications, WidgetKit & App Intents", description: "Integrate APNs push notifications via UserNotifications framework. Build Home Screen and Lock Screen widgets with WidgetKit and TimelineProvider. Create Siri-integrated App Intents for system shortcuts and Spotlight search.", resources: [{ title: "Apple — UserNotifications Framework", url: "https://developer.apple.com/documentation/usernotifications" }, { title: "WWDC 2023 — Explore App Intents", url: "https://developer.apple.com/videos/play/wwdc2023/10103/" }] },
      { section: "Advanced iOS", order: 13, title: "Testing — XCTest & UI Testing", description: "Write unit tests with XCTest, stub network calls with URLProtocol, test async code with XCTestExpectation and async test methods. Record and run UI tests with XCUITest. Measure performance with XCTMetric. Set up test coverage in Xcode.", resources: [{ title: "Apple — Testing in Xcode", url: "https://developer.apple.com/documentation/xcode/testing-your-apps-in-xcode" }, { title: "Hacking with Swift — Unit Testing", url: "https://www.hackingwithswift.com/articles/148/xcode-unit-testing-cheat-sheet" }] },
      { section: "Publishing", order: 14, title: "App Store Submission & Distribution", description: "Configure App Store Connect: app records, App Privacy, screenshots, metadata, pricing. Archive your app in Xcode, upload via Xcode Organizer or fastlane, manage certificates and provisioning profiles with Xcode's automatic signing, and navigate App Review guidelines.", resources: [{ title: "Apple — App Store Connect Help", url: "https://developer.apple.com/help/app-store-connect/" }, { title: "fastlane Documentation", url: "https://fastlane.tools" }] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // 140. ANDROID DEVELOPMENT
  // ═══════════════════════════════════════════════════════════════
  {
    title: "Android Development",
    description: "Build modern Android apps with Kotlin and Jetpack Compose — Google's recommended toolkit for native Android development. Ship to 3 billion devices on the Play Store.",
    category: "Mobile",
    icon: "Smartphone",
    steps: [
      { section: "Kotlin Fundamentals", order: 1, title: "Kotlin Language Basics", description: "Learn Kotlin's null safety (nullable types, ?., ?:, !!), type inference, data classes, sealed classes, object declarations, companion objects, extension functions, and string templates. Understand how Kotlin interops with Java.", resources: [{ title: "Kotlin Official Documentation", url: "https://kotlinlang.org/docs/home.html" }, { title: "Kotlin Koans (interactive exercises)", url: "https://play.kotlinlang.org/koans/overview" }] },
      { section: "Kotlin Fundamentals", order: 2, title: "Kotlin Coroutines & Flow", description: "Write asynchronous Kotlin with coroutines: suspend functions, CoroutineScope, Dispatchers (Main, IO, Default), launch vs async/await, structured concurrency, exception handling with SupervisorJob. Use Flow for streams, StateFlow and SharedFlow for state management.", resources: [{ title: "Kotlin Coroutines Guide (docs)", url: "https://kotlinlang.org/docs/coroutines-guide.html" }, { title: "Google Codelabs — Kotlin Coroutines", url: "https://developer.android.com/codelabs/kotlin-coroutines" }] },
      { section: "Android Studio", order: 3, title: "Android Studio & Project Structure", description: "Navigate Android Studio: project view, Logcat, Layout Editor, Device Manager, Build Variants, and Gradle build system (build.gradle.kts, dependencies, buildConfigField). Understand the Android Manifest, resource system (res/ directory), and module structure.", resources: [{ title: "Android — Android Studio Overview", url: "https://developer.android.com/studio/intro" }, { title: "Google Codelabs — Android Basics in Kotlin", url: "https://developer.android.com/courses/android-basics-kotlin/course" }] },
      { section: "Jetpack Compose", order: 4, title: "Jetpack Compose Fundamentals", description: "Build declarative UIs with Compose: @Composable functions, the recomposition model, basic composables (Text, Image, Button, TextField, LazyColumn, LazyRow), Modifier chains, layout (Column, Row, Box, ConstraintLayout), and Material 3 theming.", resources: [{ title: "Android — Compose Tutorial", url: "https://developer.android.com/jetpack/compose/tutorial" }, { title: "Google Codelabs — Jetpack Compose", url: "https://developer.android.com/courses/jetpack-compose/course" }] },
      { section: "Jetpack Compose", order: 5, title: "Compose State & Side Effects", description: "Manage state in Compose: remember, mutableStateOf, State hoisting, rememberSaveable, derivedStateOf. Handle side effects with LaunchedEffect, SideEffect, DisposableEffect, produceState, and snapshotFlow. Understand unidirectional data flow.", resources: [{ title: "Android — State in Compose", url: "https://developer.android.com/jetpack/compose/state" }, { title: "Android — Side-effects in Compose", url: "https://developer.android.com/jetpack/compose/side-effects" }] },
      { section: "Architecture", order: 6, title: "MVVM Architecture with ViewModel", description: "Implement MVVM: ViewModel (survives configuration changes), LiveData vs StateFlow for UI state, Repository pattern, separation of concerns. Use Hilt for dependency injection: @HiltViewModel, @Inject, @Module, @Provides, @Singleton, and testing with Hilt.", resources: [{ title: "Android — Guide to App Architecture", url: "https://developer.android.com/topic/architecture" }, { title: "Android — ViewModel Overview", url: "https://developer.android.com/topic/libraries/architecture/viewmodel" }] },
      { section: "Architecture", order: 7, title: "Navigation Component & Deep Links", description: "Implement navigation with Jetpack Navigation Compose: NavController, NavHost, composable() destinations, typed navigation arguments, nested nav graphs, back stack management, BottomNavigation, and deep linking with URI patterns and intent filters.", resources: [{ title: "Android — Navigation with Compose", url: "https://developer.android.com/jetpack/compose/navigation" }, { title: "Android — Deep Links", url: "https://developer.android.com/training/app-links/deep-linking" }] },
      { section: "Data Layer", order: 8, title: "Room Database", description: "Persist data with Room: @Entity (table definition), @Dao (queries with @Query, @Insert, @Update, @Delete), @Database (RoomDatabase), TypeConverters, relations (@Relation, @Embedded), migrations, and testing Room with in-memory databases.", resources: [{ title: "Android — Room Documentation", url: "https://developer.android.com/training/data-storage/room" }, { title: "Google Codelabs — Room with a View", url: "https://developer.android.com/codelabs/android-room-with-a-view-kotlin" }] },
      { section: "Data Layer", order: 9, title: "Retrofit & Networking", description: "Fetch REST APIs with Retrofit: @GET/@POST/@PUT/@DELETE annotations, Gson/Moshi/kotlinx.serialization converters, OkHttp interceptors for auth headers and logging, error handling with Response<T>, and caching strategies.", resources: [{ title: "Retrofit Documentation", url: "https://square.github.io/retrofit/" }, { title: "Android — Network Calls with Retrofit (Codelab)", url: "https://developer.android.com/codelabs/basic-android-kotlin-compose-getting-data-internet" }] },
      { section: "Advanced Android", order: 10, title: "WorkManager & Background Processing", description: "Schedule reliable background work with WorkManager: OneTimeWorkRequest, PeriodicWorkRequest, Constraints (network, charging, battery), chaining work, observing work status, and foreground services for long-running tasks like file uploads.", resources: [{ title: "Android — WorkManager Guide", url: "https://developer.android.com/topic/libraries/architecture/workmanager" }, { title: "Android — Background Work Overview", url: "https://developer.android.com/guide/background" }] },
      { section: "Advanced Android", order: 11, title: "Push Notifications (FCM) & DataStore", description: "Integrate Firebase Cloud Messaging: FCM token management, handling foreground/background notifications, notification channels. Replace SharedPreferences with DataStore (Proto and Preferences DataStore) for typed, coroutine-friendly local storage.", resources: [{ title: "Firebase — FCM Documentation", url: "https://firebase.google.com/docs/cloud-messaging/android/client" }, { title: "Android — DataStore Guide", url: "https://developer.android.com/topic/libraries/architecture/datastore" }] },
      { section: "Advanced Android", order: 12, title: "Compose Animations & Custom Drawing", description: "Build rich UIs: animate* APIs (animateDpAsState, animateColorAsState), AnimatedVisibility, AnimatedContent, updateTransition, and Crossfade. Draw custom graphics with Canvas in Compose. Implement gestures with detectTapGestures and transformable.", resources: [{ title: "Android — Animations in Compose", url: "https://developer.android.com/jetpack/compose/animation/introduction" }, { title: "Android — Graphics in Compose", url: "https://developer.android.com/jetpack/compose/graphics/draw/overview" }] },
      { section: "Testing & Publishing", order: 13, title: "Testing — Unit, Integration & UI", description: "Write unit tests with JUnit5 + Mockk/Mockito for ViewModel and Repository. Integration test Room DAOs with in-memory DB. UI test with Compose Testing (ComposeTestRule, onNodeWithText, performClick) and Espresso for View-based UI.", resources: [{ title: "Android — Testing in Compose", url: "https://developer.android.com/jetpack/compose/testing" }, { title: "Android — Testing Guide", url: "https://developer.android.com/training/testing" }] },
      { section: "Testing & Publishing", order: 14, title: "Google Play Store Submission", description: "Publish on Google Play: generate a signed APK/AAB with the keystore, create a Play Console developer account, set up the app listing (screenshots, descriptions, content rating), manage release tracks (internal, alpha, beta, production), and respond to crashes via Android Vitals.", resources: [{ title: "Google Play — Launch Checklist", url: "https://developer.android.com/distribute/best-practices/launch/launch-checklist" }, { title: "Android — App Signing", url: "https://developer.android.com/studio/publish/app-signing" }] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // 141. SPRING BOOT
  // ═══════════════════════════════════════════════════════════════
  {
    title: "Spring Boot",
    description: "Build production-grade Java backends with Spring Boot — the most popular enterprise Java framework. From REST APIs and JPA to security, caching, and microservices.",
    category: "Backend",
    icon: "Leaf",
    steps: [
      { section: "Java Foundations", order: 1, title: "Java for Spring Developers", description: "Review Java OOP essentials: interfaces, abstract classes, generics, collections (List, Map, Set), lambdas, streams API, Optional, and functional interfaces. Understand Java records, sealed classes, and modern Java 17/21 features needed for Spring Boot 3.", resources: [{ title: "Java Official Tutorials (Oracle)", url: "https://docs.oracle.com/javase/tutorial/" }, { title: "Baeldung — Java Core", url: "https://www.baeldung.com/java-tutorial" }] },
      { section: "Java Foundations", order: 2, title: "Maven & Gradle Build Tools", description: "Manage Java projects with Maven (pom.xml, lifecycle phases: clean/compile/test/package/install, dependency management, BOM) and Gradle (build.gradle.kts, tasks, dependency configurations, multi-module projects). Understand how Spring Initializr uses these tools.", resources: [{ title: "Maven in 5 Minutes (official)", url: "https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html" }, { title: "Spring Initializr", url: "https://start.spring.io" }] },
      { section: "Spring Core", order: 3, title: "Spring IoC Container & Dependency Injection", description: "Understand Spring's core: Inversion of Control, Dependency Injection (@Autowired, @Inject), Spring beans (@Component, @Service, @Repository, @Controller), ApplicationContext, bean scopes (singleton, prototype, request, session), and @Configuration + @Bean factory methods.", resources: [{ title: "Spring Framework Documentation — Core", url: "https://docs.spring.io/spring-framework/docs/current/reference/html/core.html" }, { title: "Baeldung — Spring DI Guide", url: "https://www.baeldung.com/inversion-control-and-dependency-injection-in-spring" }] },
      { section: "Spring Boot", order: 4, title: "Spring Boot Auto-Configuration & Properties", description: "How Spring Boot works: @SpringBootApplication, @EnableAutoConfiguration, conditional beans (@ConditionalOnClass, @ConditionalOnProperty), spring.factories/AutoConfiguration.imports, externalized configuration (application.properties/yml, profiles, @Value, @ConfigurationProperties), and Actuator health endpoints.", resources: [{ title: "Spring Boot Reference Documentation", url: "https://docs.spring.io/spring-boot/docs/current/reference/html/" }, { title: "Baeldung — Spring Boot Auto-Configuration", url: "https://www.baeldung.com/spring-boot-autoconfiguration" }] },
      { section: "REST APIs", order: 5, title: "REST with Spring MVC", description: "Build REST APIs: @RestController, @RequestMapping, @GetMapping/@PostMapping/@PutMapping/@DeleteMapping, @PathVariable, @RequestParam, @RequestBody, @ResponseStatus, ResponseEntity<T>. Handle global errors with @ControllerAdvice + @ExceptionHandler. Document APIs with Springdoc OpenAPI (Swagger UI).", resources: [{ title: "Spring — Building a RESTful Web Service", url: "https://spring.io/guides/gs/rest-service/" }, { title: "Baeldung — REST with Spring", url: "https://www.baeldung.com/rest-with-spring-series" }] },
      { section: "REST APIs", order: 6, title: "Input Validation & DTOs", description: "Validate incoming requests with Bean Validation (@Valid, @NotNull, @Size, @Email, @Pattern, @Min, @Max), custom validators, and handle MethodArgumentNotValidException. Use DTOs and MapStruct for mapping between entities and API responses without leaking DB structure.", resources: [{ title: "Baeldung — Spring Validation", url: "https://www.baeldung.com/spring-boot-bean-validation" }, { title: "MapStruct Documentation", url: "https://mapstruct.org/documentation/stable/reference/html/" }] },
      { section: "Data Access", order: 7, title: "Spring Data JPA & PostgreSQL", description: "Persist data with Spring Data JPA: @Entity, @Table, @Column, @Id, @GeneratedValue, relationships (@OneToMany, @ManyToOne, @ManyToMany, @OneToOne), JpaRepository (findById, save, delete, findAll), JPQL queries (@Query), Criteria API, N+1 problem and @EntityGraph fix.", resources: [{ title: "Spring Data JPA Documentation", url: "https://docs.spring.io/spring-data/jpa/docs/current/reference/html/" }, { title: "Baeldung — Spring Data JPA", url: "https://www.baeldung.com/the-persistence-layer-with-spring-data-jpa" }] },
      { section: "Data Access", order: 8, title: "Database Migrations with Flyway/Liquibase", description: "Manage schema evolution with Flyway (versioned migrations V1__init.sql, repeatable R__views.sql, baseline, repair, validate) or Liquibase (XML/YAML/SQL changelogs, rollback, diff). Integrate with Spring Boot for automatic migration on startup.", resources: [{ title: "Flyway Documentation", url: "https://documentation.red-gate.com/fd" }, { title: "Baeldung — Spring Boot with Flyway", url: "https://www.baeldung.com/database-migrations-with-flyway" }] },
      { section: "Security", order: 9, title: "Spring Security — JWT & OAuth2", description: "Secure your API with Spring Security 6: SecurityFilterChain configuration, stateless JWT authentication (filter chain, JwtAuthenticationFilter, token generation/validation), method-level security (@PreAuthorize), and OAuth2 Resource Server integration with Keycloak or Auth0.", resources: [{ title: "Spring Security Reference", url: "https://docs.spring.io/spring-security/reference/" }, { title: "Baeldung — Spring Security JWT", url: "https://www.baeldung.com/spring-security-oauth-jwt" }] },
      { section: "Performance", order: 10, title: "Caching with Redis & Spring Cache", description: "Add application-level caching: @EnableCaching, @Cacheable, @CacheEvict, @CachePut on service methods. Configure Redis as the cache provider (RedisCacheManager). Use Caffeine for in-process L1 caching. Understand cache-aside, read-through, and write-behind patterns.", resources: [{ title: "Spring — Caching Abstraction", url: "https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#cache" }, { title: "Baeldung — Spring Cache Redis", url: "https://www.baeldung.com/spring-boot-redis-cache" }] },
      { section: "Async & Events", order: 11, title: "Async Processing & Spring Events", description: "Run tasks asynchronously with @Async and ThreadPoolTaskExecutor configuration. Decouple components with Spring Application Events (@EventListener, @TransactionalEventListener, ApplicationEventPublisher). Integrate with Kafka or RabbitMQ via Spring for Apache Kafka / Spring AMQP.", resources: [{ title: "Spring — @Async Processing", url: "https://spring.io/guides/gs/async-method/" }, { title: "Baeldung — Spring Events", url: "https://www.baeldung.com/spring-events" }] },
      { section: "Testing", order: 12, title: "Testing Spring Boot Applications", description: "Test thoroughly: @SpringBootTest (full context integration tests), @WebMvcTest (controller slice tests with MockMvc), @DataJpaTest (repository slice tests with H2), Testcontainers for real PostgreSQL in tests, MockBean, @Sql scripts for test data, and Awaitility for async assertions.", resources: [{ title: "Spring Boot Testing Documentation", url: "https://docs.spring.io/spring-boot/docs/current/reference/html/testing.html" }, { title: "Testcontainers for Java", url: "https://testcontainers.com/guides/testing-spring-boot-rest-api-using-testcontainers/" }] },
      { section: "Deployment", order: 13, title: "Docker, Actuator & Production Deployment", description: "Package Spring Boot apps in Docker (layered jars, Cloud Native Buildpacks via ./mvnw spring-boot:build-image). Monitor with Actuator (health, info, metrics, Prometheus endpoint). Deploy to Railway/Render/AWS ECS/GKE. Configure HikariCP connection pool for production.", resources: [{ title: "Spring Boot — Docker Packaging", url: "https://spring.io/guides/gs/spring-boot-docker/" }, { title: "Spring Boot Actuator", url: "https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html" }] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // 142. GRAPHQL DEVELOPER
  // ═══════════════════════════════════════════════════════════════
  {
    title: "GraphQL Developer",
    description: "Design and build GraphQL APIs that give clients exactly the data they need. Master schema design, resolvers, real-time subscriptions, and production patterns with Apollo Server and Apollo Client.",
    category: "Backend",
    icon: "GitBranch",
    steps: [
      { section: "GraphQL Fundamentals", order: 1, title: "REST vs GraphQL — Core Concepts", description: "Understand why GraphQL was created: over-fetching and under-fetching problems. Learn the GraphQL type system, operations (query, mutation, subscription), introspection, the GraphQL specification, and how GraphQL differs from REST and gRPC architectures.", resources: [{ title: "GraphQL Official Documentation", url: "https://graphql.org/learn/" }, { title: "How to GraphQL (full tutorial)", url: "https://www.howtographql.com" }] },
      { section: "GraphQL Fundamentals", order: 2, title: "Schema Definition Language (SDL)", description: "Write expressive schemas with SDL: scalar types (String, Int, Float, Boolean, ID), object types, Query/Mutation/Subscription root types, non-null (!), lists, enums, input types for mutations, interfaces, unions, and schema documentation with triple-quote descriptions.", resources: [{ title: "GraphQL — Schema and Types", url: "https://graphql.org/learn/schema/" }, { title: "Apollo — Schema Basics", url: "https://www.apollographql.com/docs/apollo-server/schema/schema" }] },
      { section: "GraphQL Fundamentals", order: 3, title: "Queries, Mutations & Fragments", description: "Write effective GraphQL operations: field selection, arguments, aliases, variables ($ syntax, input types), directives (@include, @skip, @deprecated), fragments for reusable field sets, inline fragments for interfaces/unions, and named operations for debugging.", resources: [{ title: "GraphQL — Queries and Mutations", url: "https://graphql.org/learn/queries/" }, { title: "GraphQL Playground / Explorer Guide", url: "https://studio.apollographql.com/sandbox/explorer" }] },
      { section: "Apollo Server", order: 4, title: "Apollo Server Setup & Resolvers", description: "Build a GraphQL server with Apollo Server 4: typeDefs, resolvers (Query/Mutation/field resolvers), resolver chain (parent, args, context, info), returning custom errors (GraphQLError with extensions), and configuring CORS, body parser, and plugin lifecycle hooks.", resources: [{ title: "Apollo Server 4 Documentation", url: "https://www.apollographql.com/docs/apollo-server/" }, { title: "Apollo — Resolvers", url: "https://www.apollographql.com/docs/apollo-server/data/resolvers" }] },
      { section: "Apollo Server", order: 5, title: "DataLoader — Solving the N+1 Problem", description: "Eliminate N+1 database queries with DataLoader: batching and caching, creating per-request DataLoader instances in context, batch function implementation, caching strategies, and priming the cache. Essential for production GraphQL performance.", resources: [{ title: "DataLoader GitHub Repository", url: "https://github.com/graphql/dataloader" }, { title: "Shopify Engineering — Solving N+1", url: "https://shopify.engineering/solving-the-n-1-problem-for-graphql-through-batching" }] },
      { section: "Apollo Server", order: 6, title: "Authentication & Authorization", description: "Secure your GraphQL API: pass authenticated user to context via JWT verification, implement field-level authorization in resolvers, use graphql-shield for declarative permission rules, shield directives, and role-based access control patterns.", resources: [{ title: "graphql-shield Documentation", url: "https://the-guild.dev/graphql/shield" }, { title: "Apollo — Authentication and Authorization", url: "https://www.apollographql.com/docs/apollo-server/security/authentication" }] },
      { section: "Advanced Server", order: 7, title: "Subscriptions & Real-time Data", description: "Add real-time features with GraphQL subscriptions: WebSocket transport (graphql-ws), PubSub engines (in-memory, Redis-backed), filter subscriptions to specific clients, event-driven subscription resolvers, and scaling subscriptions across multiple server instances.", resources: [{ title: "Apollo — Subscriptions", url: "https://www.apollographql.com/docs/apollo-server/data/subscriptions" }, { title: "graphql-ws Documentation", url: "https://the-guild.dev/graphql/ws" }] },
      { section: "Advanced Server", order: 8, title: "Error Handling & Pagination", description: "Handle errors properly: GraphQLError extensions for machine-readable codes, formatError for scrubbing sensitive details in production, partial data with errors, and masking unexpected errors. Implement cursor-based pagination (Relay Connections spec) vs offset-based.", resources: [{ title: "Apollo — Error Handling", url: "https://www.apollographql.com/docs/apollo-server/data/errors" }, { title: "GraphQL Cursor Connections Specification", url: "https://relay.dev/graphql/connections.htm" }] },
      { section: "Apollo Client", order: 9, title: "Apollo Client with React", description: "Fetch GraphQL data in React with Apollo Client: ApolloProvider and InMemoryCache setup, useQuery (loading, error, data, refetch, fetchMore), useMutation (mutation function, variables, update cache, optimistic response), and useSubscription for real-time updates.", resources: [{ title: "Apollo Client — React Documentation", url: "https://www.apollographql.com/docs/react/" }, { title: "Apollo Client — Fetching Queries", url: "https://www.apollographql.com/docs/react/data/queries" }] },
      { section: "Apollo Client", order: 10, title: "GraphQL Code Generation", description: "Auto-generate TypeScript types and typed React hooks from your schema and operations with GraphQL Code Generator (@graphql-codegen/cli): config.yml, typescript, typescript-operations, and typescript-react-apollo plugins. Integrate into your build pipeline for end-to-end type safety.", resources: [{ title: "GraphQL Code Generator Documentation", url: "https://the-guild.dev/graphql/codegen" }, { title: "GraphQL Code Generator — React Apollo Plugin", url: "https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-react-apollo" }] },
      { section: "Production", order: 11, title: "Testing GraphQL APIs", description: "Test your GraphQL server: unit test resolver functions with mocked dataSources, integration test with Apollo Server's executeOperation, use graphql-request or Supertest for HTTP tests. Test Apollo Client in React with MockedProvider for component unit tests.", resources: [{ title: "Apollo Server — Testing", url: "https://www.apollographql.com/docs/apollo-server/testing/testing" }, { title: "Apollo Client — MockedProvider", url: "https://www.apollographql.com/docs/react/development-testing/testing" }] },
      { section: "Production", order: 12, title: "Federation & Schema Management", description: "Scale GraphQL at the organization level with Apollo Federation 2: subgraph schemas (@key, @external, @extends, @requires, @provides), the Apollo Router as the supergraph gateway, schema composition with Rover CLI, and managed federation via Apollo Studio.", resources: [{ title: "Apollo Federation Documentation", url: "https://www.apollographql.com/docs/federation/" }, { title: "Apollo Studio — Schema Registry", url: "https://www.apollographql.com/docs/graphos/schema-registry/" }] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // 143. REACT NATIVE DEVELOPER
  // ═══════════════════════════════════════════════════════════════
  {
    title: "React Native Developer",
    description: "Build cross-platform iOS and Android apps with a single codebase using React Native and Expo. Ship to both app stores with native performance, animations, and device API access.",
    category: "Mobile",
    icon: "Layers",
    steps: [
      { section: "Prerequisites", order: 1, title: "React & TypeScript Prerequisites", description: "React Native requires solid React fundamentals: functional components, all hooks (useState, useEffect, useCallback, useMemo, useRef, useContext), custom hooks, component composition, and TypeScript (interfaces, generics, discriminated unions, strict mode). Build a few React web apps first.", resources: [{ title: "React Official Documentation", url: "https://react.dev" }, { title: "Total TypeScript Free Tutorial", url: "https://www.totaltypescript.com/tutorials" }] },
      { section: "React Native Core", order: 2, title: "React Native Architecture & Core Components", description: "Understand RN's architecture: the old bridge vs new JSI/Fabric/TurboModules architecture, Metro bundler, Hermes JS engine. Master core components: View, Text, Image, TextInput, ScrollView, FlatList (keyExtractor, getItemLayout, renderItem), SectionList, and Modal.", resources: [{ title: "React Native Official Documentation", url: "https://reactnative.dev/docs/getting-started" }, { title: "React Native — Core Components", url: "https://reactnative.dev/docs/components-and-apis" }] },
      { section: "React Native Core", order: 3, title: "Expo Ecosystem & Development Workflow", description: "Set up your development environment: Expo CLI, Expo Go app for device testing, Expo managed vs bare workflow, EAS CLI. Use Expo SDK modules (expo-image, expo-camera, expo-location, expo-notifications, expo-secure-store). Debug with Flipper, React DevTools, and Expo Dev Tools.", resources: [{ title: "Expo Documentation", url: "https://docs.expo.dev" }, { title: "EAS Build Introduction", url: "https://docs.expo.dev/build/introduction/" }] },
      { section: "React Native Core", order: 4, title: "Styling — StyleSheet, NativeWind & Theming", description: "Style React Native UIs: StyleSheet API, RN's flexbox (column-first default, flex properties), Platform-specific styles (.ios.tsx/.android.tsx, Platform.OS, Platform.select), shadow and elevation, NativeWind for Tailwind CSS syntax in RN, dynamic theming with React contexts.", resources: [{ title: "React Native — StyleSheet", url: "https://reactnative.dev/docs/stylesheet" }, { title: "NativeWind Documentation", url: "https://www.nativewind.dev" }] },
      { section: "Navigation", order: 5, title: "Expo Router — File-Based Navigation", description: "Implement navigation with Expo Router v3: the app/ directory convention, Stack navigator with typed routes, Tab navigator with custom tab bars, drawer navigation, modal screens, dynamic routes with [id].tsx, deep linking configuration, and authentication flows.", resources: [{ title: "Expo Router Documentation", url: "https://expo.github.io/router/docs/" }, { title: "Expo Router — Authentication", url: "https://docs.expo.dev/router/reference/authentication/" }] },
      { section: "State & Data", order: 6, title: "State Management & Data Fetching", description: "Manage global state with Zustand (simple, performant, no boilerplate) or Redux Toolkit. Fetch and cache server data with TanStack Query (useQuery, useMutation, offline support). Persist data with MMKV (synchronous, fast) or AsyncStorage. Handle offline-first patterns.", resources: [{ title: "Zustand Documentation", url: "https://zustand-demo.pmnd.rs" }, { title: "TanStack Query — React Native", url: "https://tanstack.com/query/latest/docs/react/react-native" }] },
      { section: "Native Features", order: 7, title: "Native Device APIs", description: "Access device capabilities: expo-camera (photo/video capture, barcode scanning), expo-location (GPS coordinates, geofencing, background location), expo-image-picker (gallery access), expo-file-system (read/write files), expo-av (audio/video playback), and Haptics for tactile feedback.", resources: [{ title: "Expo SDK API Reference", url: "https://docs.expo.dev/versions/latest/" }, { title: "Expo — Permissions Guide", url: "https://docs.expo.dev/guides/permissions/" }] },
      { section: "Animations", order: 8, title: "Reanimated 3 & Gesture Handler", description: "Build smooth animations running on the UI thread: Reanimated 3 worklets, useSharedValue, useAnimatedStyle, withTiming, withSpring, withRepeat, withSequence. Handle gestures with react-native-gesture-handler: GestureDetector, Gesture.Pan, Gesture.Pinch, and composing gestures.", resources: [{ title: "React Native Reanimated 3 Documentation", url: "https://docs.swmansion.com/react-native-reanimated/" }, { title: "React Native Gesture Handler Documentation", url: "https://docs.swmansion.com/react-native-gesture-handler/" }] },
      { section: "Animations", order: 9, title: "Moti, Skia & Advanced UI", description: "Level up animations with Moti (declarative, Reanimated-based, exit animations), React Native Skia for GPU-accelerated 2D graphics (custom paint, shaders, path animations), and FlashList as a performant replacement for FlatList for large lists.", resources: [{ title: "Moti Documentation", url: "https://moti.fyi" }, { title: "React Native Skia Documentation", url: "https://shopify.github.io/react-native-skia/" }] },
      { section: "Push & Real-time", order: 10, title: "Push Notifications & Real-time Features", description: "Implement push notifications: Expo Notifications (expo-notifications), request permissions, handle foreground/background/killed state notifications, notification channels for Android, local notifications for scheduled reminders, and FCM/APNs setup for production.", resources: [{ title: "Expo Notifications Documentation", url: "https://docs.expo.dev/push-notifications/overview/" }, { title: "Expo — Setting Up Firebase Cloud Messaging", url: "https://docs.expo.dev/push-notifications/fcm-credentials/" }] },
      { section: "Build & Deploy", order: 11, title: "EAS Build & OTA Updates", description: "Build production apps with EAS: eas.json configuration (development/preview/production profiles), native module configuration, EAS Build triggers from CI, EAS Update for over-the-air JS bundle updates without App Store review, and rollout strategies.", resources: [{ title: "EAS Build Documentation", url: "https://docs.expo.dev/build/introduction/" }, { title: "EAS Update Documentation", url: "https://docs.expo.dev/eas-update/introduction/" }] },
      { section: "Build & Deploy", order: 12, title: "App Store & Google Play Submission", description: "Ship to both stores: iOS code signing (certificates, provisioning profiles, App Store Connect setup), Android keystore and upload key, EAS Submit for automated submission, App Store Optimization (keywords, screenshots, icon design), in-app purchases with RevenueCat, and crash monitoring with Sentry.", resources: [{ title: "EAS Submit Documentation", url: "https://docs.expo.dev/submit/introduction/" }, { title: "RevenueCat React Native Documentation", url: "https://www.revenuecat.com/docs/getting-started/installation/reactnative" }] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // 144. DJANGO DEVELOPER
  // ═══════════════════════════════════════════════════════════════
  {
    title: "Django Developer",
    description: "Build powerful web apps and REST APIs with Django — Python's batteries-included web framework. From ORM and templates to DRF, Celery, Redis, and production deployments.",
    category: "Backend",
    icon: "Code",
    steps: [
      { section: "Python & Django Basics", order: 1, title: "Python for Django Developers", description: "Review Python concepts essential for Django: OOP (classes, inheritance, dunder methods), decorators (@property, @staticmethod, @classmethod), generators, context managers, virtual environments (venv/pipenv/Poetry), pip, and type hints with mypy.", resources: [{ title: "The Hitchhiker's Guide to Python", url: "https://docs.python-guide.org" }, { title: "Real Python — Python Tutorials", url: "https://realpython.com" }] },
      { section: "Python & Django Basics", order: 2, title: "Django Project Structure & Settings", description: "Create and understand Django projects: manage.py commands, the apps pattern (django-admin startapp), settings.py configuration (INSTALLED_APPS, DATABASES, STATIC_URL, MEDIA_ROOT), environment-specific settings with python-decouple or django-environ, and the Django request lifecycle.", resources: [{ title: "Django Official Documentation", url: "https://docs.djangoproject.com/en/stable/" }, { title: "Django for Beginners (book preview)", url: "https://djangoforbeginners.com" }] },
      { section: "Core Django", order: 3, title: "Models, ORM & Database Migrations", description: "Define data models: field types (CharField, IntegerField, DateTimeField, ForeignKey, ManyToManyField, OneToOneField, JSONField), model Meta options (ordering, constraints, indexes), Django ORM queries (filter, exclude, annotate, aggregate, select_related, prefetch_related), and managing schema with makemigrations/migrate.", resources: [{ title: "Django — Models Documentation", url: "https://docs.djangoproject.com/en/stable/topics/db/models/" }, { title: "Django ORM Cookbook", url: "https://books.agiliq.com/projects/django-orm-cookbook/en/latest/" }] },
      { section: "Core Django", order: 4, title: "Views, URLs & Templates", description: "Build the request/response layer: function-based views (FBVs) vs class-based views (CBVs like ListView, DetailView, CreateView, UpdateView, DeleteView), URL patterns with path() and re_path(), Django template language (tags, filters, template inheritance, {% block %}, {% include %}), and context processors.", resources: [{ title: "Django — Views Documentation", url: "https://docs.djangoproject.com/en/stable/topics/http/views/" }, { title: "Classy Class-Based Views (CCBV)", url: "https://ccbv.co.uk" }] },
      { section: "Core Django", order: 5, title: "Django Forms & Authentication", description: "Handle user input with Django Forms and ModelForms (validation, cleaned_data, error rendering), use Django's built-in authentication system (login, logout, @login_required, permission_required, groups), password hashing (PBKDF2), user model customization (AbstractUser), and django-allauth for social login.", resources: [{ title: "Django — Forms Documentation", url: "https://docs.djangoproject.com/en/stable/topics/forms/" }, { title: "django-allauth Documentation", url: "https://allauth.org" }] },
      { section: "Django REST Framework", order: 6, title: "Django REST Framework — Serializers & Views", description: "Build REST APIs with DRF: Serializer and ModelSerializer (to_representation, validate_, create, update), APIView vs Generic views (ListCreateAPIView, RetrieveUpdateDestroyAPIView), ViewSets and Routers for automatic URL generation, pagination (PageNumberPagination, CursorPagination), and filtering (django-filter).", resources: [{ title: "Django REST Framework Documentation", url: "https://www.django-rest-framework.org" }, { title: "DRF — Serializers", url: "https://www.django-rest-framework.org/api-guide/serializers/" }] },
      { section: "Django REST Framework", order: 7, title: "DRF Authentication & Permissions", description: "Secure your API with DRF: built-in authentication classes (SessionAuthentication, BasicAuthentication), JWT with djangorestframework-simplejwt (token obtain/refresh/verify endpoints), custom permission classes (IsAuthenticated, IsAdminUser, IsOwnerOrReadOnly), and throttling for rate limiting.", resources: [{ title: "djangorestframework-simplejwt Documentation", url: "https://django-rest-framework-simplejwt.readthedocs.io" }, { title: "DRF — Permissions", url: "https://www.django-rest-framework.org/api-guide/permissions/" }] },
      { section: "Async & Tasks", order: 8, title: "Celery for Background Tasks", description: "Offload slow operations to background workers with Celery: @shared_task decorator, task signatures, Redis or RabbitMQ as message broker, result backends, periodic tasks with Celery Beat (crontab schedules), task routing, error handling with retry and max_retries, and monitoring with Flower.", resources: [{ title: "Celery Official Documentation", url: "https://docs.celeryq.dev/en/stable/index.html" }, { title: "Real Python — Celery with Django", url: "https://realpython.com/asynchronous-tasks-with-django-and-celery/" }] },
      { section: "Performance", order: 9, title: "Caching, Static Files & Optimization", description: "Speed up Django apps: Django cache framework with Redis (cache_page, cache_control, template fragment caching, low-level cache API), WhiteNoise for static file serving, django-storages for S3 media upload, query optimization (select_related, prefetch_related, only(), defer()), and Django Debug Toolbar.", resources: [{ title: "Django — Cache Framework", url: "https://docs.djangoproject.com/en/stable/topics/cache/" }, { title: "Django Debug Toolbar Documentation", url: "https://django-debug-toolbar.readthedocs.io" }] },
      { section: "Testing & Quality", order: 10, title: "Testing Django Applications", description: "Write robust tests: Django TestCase and SimpleTestCase, Client for making test requests, fixtures and factory_boy for test data, mocking with unittest.mock, DRF APIClient for API tests, coverage.py for measuring coverage, and pytest-django for more expressive test syntax.", resources: [{ title: "Django — Testing Documentation", url: "https://docs.djangoproject.com/en/stable/topics/testing/" }, { title: "pytest-django Documentation", url: "https://pytest-django.readthedocs.io" }] },
      { section: "Production", order: 11, title: "Docker & Production Deployment", description: "Deploy Django professionally: Dockerize with Gunicorn WSGI server + nginx reverse proxy, manage database migrations in Docker entrypoint, configure PostgreSQL (psycopg2-binary), set up environment variables with .env files, use Docker Compose for local dev, and deploy to Railway, Render, or AWS ECS.", resources: [{ title: "Djangogirls — Deployment Guide", url: "https://tutorial.djangogirls.org/en/deploy/" }, { title: "Django — Deployment Checklist", url: "https://docs.djangoproject.com/en/stable/howto/deployment/checklist/" }] },
      { section: "Production", order: 12, title: "Security, Monitoring & CI/CD", description: "Harden your Django app: ALLOWED_HOSTS, HTTPS settings (SECURE_SSL_REDIRECT, HSTS, SECURE_CONTENT_TYPE_NOSNIFF, X_FRAME_OPTIONS, CSRF_COOKIE_SECURE), django-defender for brute force protection, Sentry for error tracking, health check endpoint, and GitHub Actions CI/CD pipeline.", resources: [{ title: "Django — Security Documentation", url: "https://docs.djangoproject.com/en/stable/topics/security/" }, { title: "Sentry — Django Integration", url: "https://docs.sentry.io/platforms/python/integrations/django/" }] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // 145. UX / UI DESIGN
  // ═══════════════════════════════════════════════════════════════
  {
    title: "UX / UI Design",
    description: "Design beautiful, user-centered digital products. From research and wireframing to high-fidelity Figma designs, design systems, and developer handoff — become a T-shaped designer.",
    category: "Design",
    icon: "Palette",
    steps: [
      { section: "Design Fundamentals", order: 1, title: "Visual Design Principles", description: "Master the building blocks of great design: the Gestalt principles (proximity, similarity, continuity, closure, figure/ground), visual hierarchy through size/weight/contrast/color, grid systems (8pt grid, 12-column layouts), white space and breathing room, and the principle of progressive disclosure.", resources: [{ title: "Refactoring UI (book — highly recommended)", url: "https://www.refactoringui.com" }, { title: "Laws of UX", url: "https://lawsofux.com" }] },
      { section: "Design Fundamentals", order: 2, title: "Color Theory for UI Design", description: "Apply color effectively: HSL vs RGB vs HEX color models, color harmonies (complementary, analogous, triadic, split-complementary), building accessible color palettes (WCAG contrast ratios for AA/AAA), semantic color tokens (primary, secondary, semantic states), dark mode palette creation.", resources: [{ title: "Material Design — Color System", url: "https://m3.material.io/styles/color/overview" }, { title: "Huemint — AI Color Palette Generator", url: "https://huemint.com" }] },
      { section: "Design Fundamentals", order: 3, title: "Typography for Digital Interfaces", description: "Use type effectively in UIs: type scales and modular scale (1.25, 1.333, 1.5 ratios), font pairing principles, choosing between serif/sans-serif/monospace for different contexts, line-height and letter-spacing, maximum line length (45-75 characters), variable fonts, and Google Fonts + font loading performance.", resources: [{ title: "Typescale — Modular Scale Generator", url: "https://typescale.com" }, { title: "Fonts Knowledge (Google)", url: "https://fonts.google.com/knowledge" }] },
      { section: "UX Process", order: 4, title: "Design Thinking & User Research", description: "Follow the design process: Empathize (user interviews, contextual inquiry, surveys), Define (user personas, empathy maps, problem statements, How Might We questions), Ideate (brainstorming, crazy eights, SCAMPER), Prototype (paper, digital), and Test (usability testing, A/B testing, 5-second test).", resources: [{ title: "NNGroup — Design Thinking 101", url: "https://www.nngroup.com/articles/design-thinking/" }, { title: "Google Design Sprint Kit", url: "https://designsprintkit.withgoogle.com" }] },
      { section: "UX Process", order: 5, title: "Information Architecture & User Flows", description: "Structure digital products: card sorting (open vs closed) for navigation, site maps, content hierarchy, user journey maps (touchpoints, emotions, opportunities), user flow diagrams (happy path + edge cases), task analysis, and mental model alignment.", resources: [{ title: "NNGroup — Information Architecture (article)", url: "https://www.nngroup.com/articles/information-architecture-study-guide/" }, { title: "Optimal Workshop — Card Sorting Guide", url: "https://www.optimalworkshop.com/101/card-sorting" }] },
      { section: "Figma Mastery", order: 6, title: "Figma — Core Tools & Techniques", description: "Master Figma: the interface (layers panel, properties panel, canvas), vector drawing (Pen tool, boolean operations), Auto Layout (padding, spacing, fill/fixed/hug), component architecture (main components, instances, variants, props), and organizing large files with pages and sections.", resources: [{ title: "Figma — Learn Design (official tutorials)", url: "https://www.figma.com/resources/learn-design/" }, { title: "Figma Crash Course (YouTube)", url: "https://www.youtube.com/watch?v=FTFaQWZBqQ8" }] },
      { section: "Figma Mastery", order: 7, title: "Figma — Components, Variables & Prototyping", description: "Build production-ready Figma files: component variants with properties (Boolean, Text, Instance Swap), nested components, slot patterns, Figma Variables for design tokens (color/spacing/typography modes for light/dark theme), interactive prototyping (Smart Animate, scroll, overlays), and sharing for user testing.", resources: [{ title: "Figma — Variables Guide", url: "https://help.figma.com/hc/en-us/articles/15339657135383-Guide-to-variables-in-Figma" }, { title: "Figma — Component Properties", url: "https://www.figma.com/blog/announcing-component-properties/" }] },
      { section: "Design Systems", order: 8, title: "Design Systems & Component Libraries", description: "Build scalable design systems: atomic design methodology (atoms, molecules, organisms, templates, pages), token taxonomy (color, spacing, typography, shadow, border-radius, motion), documentation in Figma and Storybook, versioning components, and contributing to/referencing systems like Material 3, Radix, and Ant Design.", resources: [{ title: "designsystems.com — Guides and Articles", url: "https://www.designsystems.com" }, { title: "Brad Frost — Atomic Design (free book)", url: "https://atomicdesign.bradfrost.com" }] },
      { section: "Accessibility & Usability", order: 9, title: "Accessibility in Design", description: "Design for everyone: WCAG 2.1 and 2.2 guidelines (perceivable, operable, understandable, robust), color contrast ratios (4.5:1 for AA normal text), focus indicator design, touch target sizing (44×44px minimum), cognitive load reduction, designing for screen readers (reading order, alt text for images), and reduced motion preferences.", resources: [{ title: "WebAIM — Contrast Checker", url: "https://webaim.org/resources/contrastchecker/" }, { title: "NNGroup — Accessibility for Designers", url: "https://www.nngroup.com/articles/keyboard-accessibility/" }] },
      { section: "Accessibility & Usability", order: 10, title: "Usability Testing & Iteration", description: "Validate your designs: moderated vs unmoderated usability testing, recruiting participants (5 users rule), writing test scripts and tasks, facilitating sessions without leading, synthesizing observations into insights, heat maps and session recordings (Hotjar, FullStory), and rapid iteration cycles.", resources: [{ title: "NNGroup — Usability Testing Guide", url: "https://www.nngroup.com/articles/usability-testing-101/" }, { title: "Maze — Unmoderated Testing Platform", url: "https://maze.co" }] },
      { section: "Developer Handoff", order: 11, title: "Developer Handoff & Motion Design", description: "Bridge design and engineering: design redlines in Figma (Inspect panel, CSS code generation, iOS/Android specs), component documentation with annotations, design tokens export (Style Dictionary, Tokens Studio plugin), micro-interaction specifications with Figma prototyping and After Effects/Lottie for complex animations.", resources: [{ title: "Tokens Studio for Figma (plugin)", url: "https://tokens.studio" }, { title: "LottieFiles — Animate for the Web", url: "https://lottiefiles.com" }] },
      { section: "Career", order: 12, title: "Portfolio & Career in Design", description: "Land a design role: building a portfolio (3-5 case studies with problem → process → outcome narrative), writing great case study copy, self-hosted portfolio vs Behance vs Notion, preparing for design critiques and take-home exercises, salary research (Levels.fyi, Design Census), and contributing to open-source design.", resources: [{ title: "UX Portfolio Tips (NNGroup)", url: "https://www.nngroup.com/articles/ux-portfolio-study-guide/" }, { title: "Design Census (annual salary report)", url: "https://design.google/library/design-census-2023/" }] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // 146. MLOPS ENGINEER
  // ═══════════════════════════════════════════════════════════════
  {
    title: "MLOps Engineer",
    description: "Bridge the gap between ML research and production. Build pipelines that train, version, serve, and monitor machine learning models reliably at scale using modern MLOps tooling.",
    category: "AI/ML",
    icon: "Cpu",
    steps: [
      { section: "Foundations", order: 1, title: "ML Fundamentals for MLOps", description: "Understand what you're operationalizing: supervised/unsupervised/reinforcement learning concepts, the ML project lifecycle (data → training → evaluation → deployment → monitoring), key metrics (accuracy, F1, AUC-ROC, RMSE), model artifacts (weights, parameters, hyperparameters), and why ML in production is hard.", resources: [{ title: "Google — Machine Learning Crash Course", url: "https://developers.google.com/machine-learning/crash-course" }, { title: "Full Stack Deep Learning — Lecture 1", url: "https://fullstackdeeplearning.com/course/2022/lecture-1-course-vision-and-when-to-use-ml/" }] },
      { section: "Foundations", order: 2, title: "Python & Docker for MLOps", description: "Containerize ML: Dockerfile for Python ML environments (CUDA base images, multi-stage builds to minimize size), requirements.txt vs conda environment.yml, GPU access in Docker (--gpus, nvidia-docker), docker-compose for local ML stacks (DB + model server + monitoring), and building reproducible images.", resources: [{ title: "Docker Curriculum (free)", url: "https://docker-curriculum.com" }, { title: "NVIDIA Container Toolkit", url: "https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html" }] },
      { section: "Experiment Tracking", order: 3, title: "MLflow — Experiment Tracking & Model Registry", description: "Track ML experiments with MLflow: mlflow.start_run(), logging params/metrics/artifacts, MLflow UI, comparing runs, MLflow Projects for reproducibility, and the Model Registry (registering models, stage transitions: Staging → Production, annotations). Self-host or use Databricks Managed MLflow.", resources: [{ title: "MLflow Official Documentation", url: "https://mlflow.org/docs/latest/index.html" }, { title: "MLflow Quickstart", url: "https://mlflow.org/docs/latest/quickstart.html" }] },
      { section: "Experiment Tracking", order: 4, title: "Weights & Biases (W&B) for ML Teams", description: "Use W&B for collaborative ML: wandb.init(), wandb.log() for metrics, artifact versioning (datasets, models), W&B Sweeps for hyperparameter optimization (grid, random, Bayes), Run comparison UI, W&B Tables for rich dataset visualization, and Reports for sharing results.", resources: [{ title: "W&B Documentation", url: "https://docs.wandb.ai" }, { title: "W&B — MLOps Course (free)", url: "https://www.wandb.courses/courses/mlops-course" }] },
      { section: "Data & Pipelines", order: 5, title: "DVC — Data Version Control", description: "Version data and models like code with DVC: dvc init, dvc add large files, remote storage (S3, GCS, Azure Blob), dvc push/pull, DVC pipelines (dvc.yaml, stages, dependencies, outputs), dvc repro for pipeline reproduction, and integrating DVC with Git for complete experiment reproducibility.", resources: [{ title: "DVC Official Documentation", url: "https://dvc.org/doc" }, { title: "DVC — Get Started Tutorial", url: "https://dvc.org/doc/start" }] },
      { section: "Data & Pipelines", order: 6, title: "Feature Stores & Data Pipelines", description: "Centralize feature engineering with Feast: feature views, entities, point-in-time correct historical data retrieval for training, online store for low-latency inference. Build training data pipelines with Apache Airflow or Prefect. Validate data quality with Great Expectations.", resources: [{ title: "Feast Documentation", url: "https://docs.feast.dev" }, { title: "Great Expectations Documentation", url: "https://docs.greatexpectations.io" }] },
      { section: "Model Serving", order: 7, title: "Model Serving — FastAPI, BentoML & Triton", description: "Serve models in production: build inference APIs with FastAPI (request validation, async handlers, GPU batching), package models with BentoML (runners, services, Bento containerization), and high-throughput serving with NVIDIA Triton Inference Server (dynamic batching, model ensemble, concurrent execution).", resources: [{ title: "BentoML Documentation", url: "https://docs.bentoml.com" }, { title: "NVIDIA Triton Server (GitHub)", url: "https://github.com/triton-inference-server/server" }] },
      { section: "CI/CD for ML", order: 8, title: "CI/CD for Machine Learning", description: "Apply software engineering discipline to ML: GitHub Actions workflows for data validation → model training → evaluation → registration → deployment, CML (Continuous Machine Learning) for metrics reporting in PRs, automated model tests (output shape, latency, accuracy thresholds), and GitOps for ML model deployment.", resources: [{ title: "CML — Continuous Machine Learning (DVC)", url: "https://cml.dev" }, { title: "MLOps Community — CI/CD for ML", url: "https://mlops.community" }] },
      { section: "Kubernetes for ML", order: 9, title: "Kubernetes for ML Workloads", description: "Run ML on Kubernetes: Kubeflow for end-to-end ML workflows (Pipelines, Notebook Servers, KServe for model serving), KFServing/KServe for serverless model inference (InferenceService, canary deployments, traffic splitting), GPU node pools, and resource quotas for GPU scheduling.", resources: [{ title: "Kubeflow Documentation", url: "https://www.kubeflow.org/docs/" }, { title: "KServe Documentation", url: "https://kserve.github.io/website/latest/" }] },
      { section: "Monitoring", order: 10, title: "Model Monitoring & Drift Detection", description: "Monitor models in production: data drift (feature distribution changes, Kolmogorov-Smirnov test, Population Stability Index), concept drift (prediction distribution changes), performance degradation tracking, Evidently AI for drift reports and test suites, Prometheus metrics for latency/throughput/error rates, and alerting rules.", resources: [{ title: "Evidently AI Documentation", url: "https://docs.evidentlyai.com" }, { title: "Arize AI — ML Observability Guide", url: "https://arize.com/blog-course/" }] },
      { section: "Cloud ML", order: 11, title: "Cloud ML Platforms — SageMaker & Vertex AI", description: "Use managed cloud ML: AWS SageMaker (Training Jobs, Processing Jobs, Pipelines, Model Registry, Real-time Endpoints, Batch Transform), Google Vertex AI (Training, Pipelines, Model Registry, Prediction endpoints, Matching Engine for vector search), and cost optimization strategies.", resources: [{ title: "AWS SageMaker Documentation", url: "https://docs.aws.amazon.com/sagemaker/" }, { title: "Google Vertex AI Documentation", url: "https://cloud.google.com/vertex-ai/docs" }] },
      { section: "Security & Governance", order: 12, title: "ML Security, Bias & Governance", description: "Responsible MLOps: model bias detection and fairness metrics (demographic parity, equalized odds) with Fairlearn or Aequitas, adversarial attacks and defense (FGSM, PGD, adversarial training), model cards for documentation, data governance and lineage tracking (OpenLineage, Datahub), and GDPR compliance for ML.", resources: [{ title: "Fairlearn Documentation", url: "https://fairlearn.org" }, { title: "Model Cards for Model Reporting (Google Research)", url: "https://arxiv.org/abs/1810.03993" }] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // 147. SOFTWARE ARCHITECTURE
  // ═══════════════════════════════════════════════════════════════
  {
    title: "Software Architecture",
    description: "Design systems that scale — from clean code and design patterns to distributed architectures, event-driven systems, and cloud-native patterns. Think like a principal engineer.",
    category: "Architecture",
    icon: "Layout",
    steps: [
      { section: "Design Principles", order: 1, title: "SOLID Principles & Clean Code", description: "Write maintainable code: Single Responsibility (one reason to change), Open/Closed (open for extension, closed for modification), Liskov Substitution (subtypes substitute base types), Interface Segregation (specific interfaces over fat ones), Dependency Inversion (depend on abstractions). Apply DRY, KISS, YAGNI, and Law of Demeter.", resources: [{ title: "Clean Code — Robert C. Martin (book)", url: "https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882" }, { title: "SOLID Principles Explained (Digital Ocean)", url: "https://www.digitalocean.com/community/conceptual-articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design" }] },
      { section: "Design Patterns", order: 2, title: "Design Patterns — GoF Catalog", description: "Recognize and apply the 23 Gang of Four patterns: Creational (Singleton, Factory Method, Abstract Factory, Builder, Prototype), Structural (Adapter, Bridge, Composite, Decorator, Facade, Flyweight, Proxy), and Behavioral (Command, Observer, Strategy, Template Method, Iterator, State, Chain of Responsibility, Mediator, Visitor).", resources: [{ title: "Refactoring.Guru — Design Patterns (free)", url: "https://refactoring.guru/design-patterns" }, { title: "Design Patterns: Elements of Reusable OO Software (book)", url: "https://en.wikipedia.org/wiki/Design_Patterns" }] },
      { section: "Application Architecture", order: 3, title: "Layered & Hexagonal Architecture", description: "Organize application code: classic N-tier (Presentation → Business Logic → Data), Hexagonal Architecture (ports and adapters), Onion Architecture, Clean Architecture (entities → use cases → interface adapters → frameworks). Understand dependency rules, testability benefits, and when to apply each.", resources: [{ title: "The Clean Architecture (Robert Martin blog)", url: "https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html" }, { title: "Hexagonal Architecture (Alistair Cockburn)", url: "https://alistair.cockburn.us/hexagonal-architecture/" }] },
      { section: "Distributed Systems", order: 4, title: "Microservices vs Monolith", description: "Choose the right architectural style: monolith (single deployable, simpler ACID, easier debugging) vs microservices (independent deployability, bounded contexts, polyglot persistence, team autonomy). Understand the Strangler Fig pattern for migration, service boundaries via Domain-Driven Design, and the modular monolith as a middle ground.", resources: [{ title: "Martin Fowler — Microservices (article)", url: "https://martinfowler.com/articles/microservices.html" }, { title: "Sam Newman — Building Microservices (book)", url: "https://samnewman.io/books/building_microservices/" }] },
      { section: "Distributed Systems", order: 5, title: "API Design — REST, GraphQL & gRPC", description: "Design APIs that last: REST best practices (resource naming, versioning, HATEOAS, idempotency, error formats using RFC 7807), GraphQL for flexible client queries (schema-first, Federation), and gRPC for high-performance internal services (Protocol Buffers, streaming, code generation, deadlines).", resources: [{ title: "Google API Design Guide", url: "https://cloud.google.com/apis/design" }, { title: "gRPC Documentation", url: "https://grpc.io/docs/" }] },
      { section: "Event-Driven", order: 6, title: "Event-Driven Architecture & CQRS/Event Sourcing", description: "Build loosely coupled systems: event-driven architecture (events as facts, pub/sub, choreography vs orchestration), CQRS (separate read/write models, projections), Event Sourcing (event log as source of truth, replaying events, snapshots), and the Saga pattern for distributed transactions.", resources: [{ title: "Martin Fowler — Event Sourcing", url: "https://martinfowler.com/eaaDev/EventSourcing.html" }, { title: "Microsoft — CQRS Pattern", url: "https://learn.microsoft.com/en-us/azure/architecture/patterns/cqrs" }] },
      { section: "Scalability", order: 7, title: "Caching Strategies & Data Consistency", description: "Design for performance: cache-aside, read-through, write-through, write-behind, and refresh-ahead caching patterns; cache invalidation strategies; CDN for edge caching; eventual consistency vs strong consistency; CAP theorem and PACELC; distributed locking (Redlock); and database read replicas for horizontal read scaling.", resources: [{ title: "Martin Fowler — Patterns of Enterprise Application Architecture", url: "https://martinfowler.com/books/eaa.html" }, { title: "Designing Data-Intensive Applications (Kleppmann book)", url: "https://dataintensive.net" }] },
      { section: "Scalability", order: 8, title: "Message Queues, Kafka & Async Patterns", description: "Decouple services with messaging: point-to-point queues (RabbitMQ, SQS) vs pub/sub topics (Kafka, SNS), Kafka architecture (brokers, topics, partitions, consumer groups, offsets), message delivery guarantees (at-most-once, at-least-once, exactly-once semantics), the outbox pattern for reliable event publishing.", resources: [{ title: "Confluent — Kafka: The Definitive Guide (free)", url: "https://www.confluent.io/resources/kafka-the-definitive-guide-v2/" }, { title: "RabbitMQ Tutorials", url: "https://www.rabbitmq.com/getstarted.html" }] },
      { section: "Reliability", order: 9, title: "Resilience Patterns & Circuit Breakers", description: "Build fault-tolerant systems: circuit breaker pattern (closed/open/half-open states), retry with exponential backoff and jitter, bulkhead isolation, timeout enforcement, rate limiting (token bucket, leaky bucket), graceful degradation, feature flags for operational control, and chaos engineering principles.", resources: [{ title: "Microsoft — Cloud Design Patterns", url: "https://learn.microsoft.com/en-us/azure/architecture/patterns/" }, { title: "Netflix Tech Blog — Hystrix", url: "https://netflixtechblog.com/making-the-netflix-api-more-resilient-a8ec62159c2d" }] },
      { section: "Documentation", order: 10, title: "Architecture Documentation — C4 Model", description: "Communicate architecture clearly: C4 model (Context, Container, Component, Code diagrams), Architecture Decision Records (ADR) for capturing key decisions, RFC process for team alignment, using PlantUML, Mermaid, or Structurizr DSL for diagrams-as-code, and keeping architecture documentation current.", resources: [{ title: "C4 Model Official Site", url: "https://c4model.com" }, { title: "Architecture Decision Records (GitHub)", url: "https://adr.github.io" }] },
      { section: "Cloud-Native", order: 11, title: "Cloud-Native Architecture Patterns", description: "Design for the cloud: 12-Factor App methodology, sidecar and ambassador container patterns, service mesh (Istio, Linkerd for mTLS, traffic management, observability), GitOps for infrastructure (ArgoCD, Flux), multi-tenancy patterns, and the Well-Architected Framework (operational excellence, security, reliability, performance, cost).", resources: [{ title: "12factor.net", url: "https://12factor.net" }, { title: "AWS Well-Architected Framework", url: "https://aws.amazon.com/architecture/well-architected/" }] },
      { section: "Career", order: 12, title: "System Design Interviews & Architect Role", description: "Become a recognized architect: practice system design (URL shortener, Twitter feed, distributed cache, ride-sharing backend), study popular system designs (Netflix, Uber, WhatsApp), understand trade-off discussions, write RFCs and ADRs, build credibility through code review leadership, and transition paths from senior engineer to staff/principal/architect.", resources: [{ title: "System Design Primer (GitHub)", url: "https://github.com/donnemartin/system-design-primer" }, { title: "Grokking System Design Interview (Educative)", url: "https://www.educative.io/courses/grokking-the-system-design-interview" }] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // 148. PROMPT ENGINEERING
  // ═══════════════════════════════════════════════════════════════
  {
    title: "Prompt Engineering",
    description: "Master the art and science of communicating with large language models. Build LLM-powered applications, RAG pipelines, and autonomous agents using cutting-edge prompting techniques.",
    category: "AI/ML",
    icon: "MessageSquare",
    steps: [
      { section: "LLM Fundamentals", order: 1, title: "How LLMs Work — Foundations", description: "Understand the technology you're working with: transformer architecture (self-attention, positional encoding, encoder-decoder), tokenization (BPE, SentencePiece, tiktoken — counting tokens), training (pre-training on web data, fine-tuning, RLHF), context windows (4K to 1M tokens), temperature and sampling (top-k, top-p, greedy decoding).", resources: [{ title: "Andrej Karpathy — Intro to LLMs (YouTube)", url: "https://www.youtube.com/watch?v=zjkBMFhNj_g" }, { title: "3Blue1Brown — Transformers", url: "https://www.youtube.com/watch?v=wjZofJX0v4M" }] },
      { section: "Core Techniques", order: 2, title: "Prompt Anatomy & System Prompts", description: "Structure effective prompts: the system/user/assistant message roles, crafting system prompts (persona, context, constraints, output format), writing clear user messages, managing conversation history (message arrays), and understanding how different model providers (OpenAI, Anthropic, Google, Meta) differ in prompt sensitivity.", resources: [{ title: "OpenAI — Prompt Engineering Guide", url: "https://platform.openai.com/docs/guides/prompt-engineering" }, { title: "Anthropic — Claude Prompt Library", url: "https://docs.anthropic.com/en/prompt-library/" }] },
      { section: "Core Techniques", order: 3, title: "Zero-Shot, Few-Shot & Chain-of-Thought", description: "Master core prompting paradigms: zero-shot (asking without examples), one-shot and few-shot (in-context learning with examples), chain-of-thought prompting (\"think step by step\"), zero-shot CoT, self-consistency (multiple reasoning paths, majority vote), and tree-of-thought for complex multi-step problems.", resources: [{ title: "Chain-of-Thought Prompting (Google Research paper)", url: "https://arxiv.org/abs/2201.11903" }, { title: "Prompt Engineering Guide (DAIR.AI)", url: "https://www.promptingguide.ai" }] },
      { section: "Core Techniques", order: 4, title: "Advanced Prompting — ReAct, ToT & Meta-Prompting", description: "Push beyond basic prompting: ReAct (Reasoning + Acting — interleave thought and action for tool-using agents), Tree-of-Thoughts (parallel reasoning branches), meta-prompting (prompt the model to generate its own prompts), self-refinement (model critiques and revises its own output), and least-to-most prompting for decomposing complex tasks.", resources: [{ title: "ReAct: Synergizing Reasoning and Acting (paper)", url: "https://arxiv.org/abs/2210.03629" }, { title: "Tree of Thoughts (paper)", url: "https://arxiv.org/abs/2305.10601" }] },
      { section: "Output Control", order: 5, title: "Structured Output & Output Formatting", description: "Get reliable, machine-parseable output: JSON mode and structured outputs (OpenAI Structured Outputs, Anthropic JSON), Pydantic models for output validation, instructing markdown vs plain text output, constrained generation (Outlines, LMQL), and extracting structured data from unstructured text reliably.", resources: [{ title: "OpenAI — Structured Outputs", url: "https://platform.openai.com/docs/guides/structured-outputs" }, { title: "Outlines — Structured Text Generation", url: "https://outlines-dev.github.io/outlines/" }] },
      { section: "RAG", order: 6, title: "Retrieval-Augmented Generation (RAG)", description: "Ground LLM responses in your data: text chunking strategies (fixed-size, semantic, recursive), embedding models (OpenAI text-embedding-3, Cohere, local models), vector databases (Pinecone, Weaviate, Chroma, pgvector), similarity search (cosine, dot product, HNSW), query rewriting, HyDE, and re-ranking for better recall.", resources: [{ title: "LlamaIndex — Building RAG Applications", url: "https://docs.llamaindex.ai/en/stable/getting_started/starter_example/" }, { title: "RAG Survey Paper (arxiv)", url: "https://arxiv.org/abs/2312.10997" }] },
      { section: "Agents & Tools", order: 7, title: "Tool Use & Function Calling", description: "Give LLMs tools: OpenAI function calling and tool use, defining tool schemas (name, description, parameters as JSON Schema), the tool-use loop (model → tool call → execute → result → model), parallel tool calls, error handling when tools fail, and building reliable tool-using workflows.", resources: [{ title: "OpenAI — Function Calling Guide", url: "https://platform.openai.com/docs/guides/function-calling" }, { title: "Anthropic — Tool Use Guide", url: "https://docs.anthropic.com/en/docs/build-with-claude/tool-use" }] },
      { section: "Agents & Tools", order: 8, title: "LLM Agents & Multi-Agent Systems", description: "Build autonomous agents: the ReAct agent loop, LangChain agents and AgentExecutor, LangGraph for stateful multi-step agent workflows (state machines, conditional edges, cycles), CrewAI for role-based multi-agent teams, memory types (in-context, external/vector, entity memory), and managing agent reliability.", resources: [{ title: "LangGraph Documentation", url: "https://langchain-ai.github.io/langgraph/" }, { title: "CrewAI Documentation", url: "https://docs.crewai.com" }] },
      { section: "Production", order: 9, title: "Prompt Security — Injection Defense", description: "Protect LLM applications: prompt injection attacks (direct and indirect), jailbreaking techniques (DAN, role play, base64 encoding), defense strategies (input validation, output filtering, prompt hardening, sandboxing tool calls), LLM firewalls (LlamaGuard, Nemo Guardrails), and red-teaming your AI application.", resources: [{ title: "OWASP — Top 10 for LLM Applications", url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" }, { title: "Simon Willison — Prompt Injection Attacks", url: "https://simonwillison.net/2022/Sep/12/prompt-injection/" }] },
      { section: "Production", order: 10, title: "Evaluation & A/B Testing Prompts", description: "Measure prompt quality scientifically: building eval datasets (golden sets, adversarial examples, edge cases), LLM-as-judge evaluation (using GPT-4 to score responses), RAGAS for RAG evaluation (faithfulness, answer relevancy, context recall), A/B testing prompt variants with statistical significance, and tracking regressions with CI evals.", resources: [{ title: "RAGAS — RAG Evaluation Framework", url: "https://docs.ragas.io" }, { title: "Brainlid — LLM Evaluation Guide", url: "https://www.brainlid.org/ai/2023/09/26/llm-evaluation.html" }] },
      { section: "Production", order: 11, title: "Production Prompt Management & Optimization", description: "Operationalize prompts: prompt versioning (PromptLayer, LangSmith), managing prompts as code vs in a CMS, caching identical requests (semantic caching with Redis + embeddings), cost optimization (prompt compression with LLMLingua, choosing cheaper models for simpler tasks), latency reduction (streaming, async parallel calls), and observability with LangSmith/Langfuse.", resources: [{ title: "LangSmith Documentation", url: "https://docs.smith.langchain.com" }, { title: "LLMLingua — Prompt Compression", url: "https://llmlingua.com" }] },
      { section: "Fine-Tuning", order: 12, title: "Fine-Tuning vs Prompting — When & How", description: "Decide when to fine-tune: prompting vs few-shot vs RAG vs fine-tuning trade-offs (cost, latency, quality), LoRA and QLoRA for parameter-efficient fine-tuning, OpenAI fine-tuning API, Hugging Face PEFT library, preparing training data (instruction-response pairs, quality over quantity), and evaluating fine-tuned model quality.", resources: [{ title: "OpenAI — Fine-Tuning Guide", url: "https://platform.openai.com/docs/guides/fine-tuning" }, { title: "HuggingFace PEFT Documentation", url: "https://huggingface.co/docs/peft/index" }] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // 149. COMPUTER SCIENCE FUNDAMENTALS
  // ═══════════════════════════════════════════════════════════════
  {
    title: "Computer Science Fundamentals",
    description: "Build the theoretical foundation that makes you a better engineer. From binary math and data structures to algorithms, operating systems, and compiler theory — CS first principles.",
    category: "Fundamentals",
    icon: "BookOpen",
    steps: [
      { section: "Math & Logic", order: 1, title: "Binary, Number Systems & Boolean Algebra", description: "Understand how computers represent data: binary (base-2), hexadecimal (base-16), octal (base-8), converting between systems, two's complement for signed integers, floating-point representation (IEEE 754), bit manipulation operations (AND, OR, XOR, NOT, shift), and Boolean algebra laws (De Morgan's, absorption, distribution).", resources: [{ title: "CS50 — Week 0 (Binary, ASCII, RGB)", url: "https://cs50.harvard.edu/x/2024/weeks/0/" }, { title: "Khan Academy — Number Bases", url: "https://www.khanacademy.org/computing/ap-computer-science-principles/computers-101/digital-data-representation/a/binary-numbers" }] },
      { section: "Data Structures", order: 2, title: "Arrays, Strings & Linked Lists", description: "Master foundational data structures: dynamic arrays (amortized O(1) append), multidimensional arrays, string immutability and interning, singly vs doubly linked lists (insert/delete O(1) with pointer, search O(n)), circular linked lists, skip lists for probabilistic fast search, and memory layout implications.", resources: [{ title: "CS50 — Week 5 (Data Structures)", url: "https://cs50.harvard.edu/x/2024/weeks/5/" }, { title: "Visualgo — Data Structure Animations", url: "https://visualgo.net/en" }] },
      { section: "Data Structures", order: 3, title: "Stacks, Queues & Hash Tables", description: "Use the right data structure: stack (LIFO, call stack simulation, undo/redo, expression evaluation, DFS), queue (FIFO, BFS, scheduling, deque for double-ended access), priority queue with binary heap (heapify, heap sort, Dijkstra), and hash tables (hash functions, collision resolution: chaining vs open addressing, load factor, rehashing).", resources: [{ title: "Basecs — Hash Tables (free blog series)", url: "https://medium.com/basecs/taking-hash-tables-off-the-shelf-139cbf4752f0" }, { title: "CLRS — Introduction to Algorithms (book)", url: "https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/" }] },
      { section: "Data Structures", order: 4, title: "Trees — Binary, BST, AVL & Heaps", description: "Master tree structures: binary trees (BFS/DFS traversals: inorder, preorder, postorder), binary search trees (insert, search, delete O(log n) average), BST problems (lowest common ancestor, balanced check, serialize/deserialize), self-balancing AVL trees (rotation rules), Red-Black trees, and min/max heaps.", resources: [{ title: "Visualgo — Binary Search Tree", url: "https://visualgo.net/en/bst" }, { title: "MIT 6.006 — Trees (lecture)", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/pages/lecture-notes/" }] },
      { section: "Data Structures", order: 5, title: "Graphs — Representations, BFS & DFS", description: "Work with graph problems: adjacency matrix vs adjacency list (space/time trade-offs), directed vs undirected vs weighted graphs, Breadth-First Search (shortest path in unweighted, level-order traversal, bipartite check), Depth-First Search (cycle detection, topological sort, SCC with Tarjan's/Kosaraju's algorithms).", resources: [{ title: "Basecs — Graph Theory Series", url: "https://medium.com/basecs/from-theory-to-practice-representing-graphs-cfd782c5be38" }, { title: "NeetCode — Graph Playlist (YouTube)", url: "https://www.youtube.com/c/NeetCode" }] },
      { section: "Algorithms", order: 6, title: "Big-O Notation & Complexity Analysis", description: "Analyze algorithms rigorously: Big-O (worst case), Big-Θ (tight bound), Big-Ω (lower bound), time and space complexity of common operations, amortized analysis, master theorem for recurrence relations, and understanding when O(n log n) matters more than a constant factor in practice.", resources: [{ title: "Big-O Cheat Sheet", url: "https://www.bigocheatsheet.com" }, { title: "MIT 6.006 — Lecture 1: Algorithmic Thinking", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/" }] },
      { section: "Algorithms", order: 7, title: "Sorting Algorithms", description: "Implement and analyze all major sorts: Bubble, Selection, Insertion (O(n²) but good for small/nearly sorted), Merge Sort (O(n log n), stable, divide and conquer), Quick Sort (O(n log n) average, in-place, pivot strategies), Heap Sort (O(n log n), in-place), Counting/Radix/Bucket Sort (O(n) for integer keys).", resources: [{ title: "Sorting Algorithms Animations (toptal)", url: "https://www.toptal.com/developers/sorting-algorithms" }, { title: "Visualgo — Sorting", url: "https://visualgo.net/en/sorting" }] },
      { section: "Algorithms", order: 8, title: "Recursion & Dynamic Programming", description: "Solve complex problems with recursion and DP: base case + recursive case, call stack and stack overflow risk, memoization (top-down DP) converting recursion to O(n) time, tabulation (bottom-up DP), 1D DP problems (Fibonacci, climb stairs, coin change), 2D DP (longest common subsequence, edit distance, knapsack), and space optimization.", resources: [{ title: "Dynamic Programming for Beginners (NeetCode)", url: "https://www.youtube.com/watch?v=oBt53YbR9Kk" }, { title: "AlgoMonster — DP Patterns", url: "https://algo.monster/problems/dynamic-programming-intro" }] },
      { section: "Systems", order: 9, title: "Memory Management & Pointers", description: "Understand computer memory: stack vs heap allocation, pointer arithmetic, manual memory management (malloc/free) and memory leaks, garbage collection strategies (mark-and-sweep, reference counting, generational GC), virtual memory (pages, page tables, TLB, page faults), and memory-mapped files.", resources: [{ title: "CS50 — Week 4 (Memory)", url: "https://cs50.harvard.edu/x/2024/weeks/4/" }, { title: "Beej's Guide to C Programming (free)", url: "https://beej.us/guide/bgc/" }] },
      { section: "Systems", order: 10, title: "Operating Systems — Processes & Concurrency", description: "Understand what runs your code: process vs thread vs goroutine/fiber, the scheduler (Round Robin, CFS, preemptive vs cooperative multitasking), context switching overhead, concurrency primitives (mutex, semaphore, condition variable, read-write lock), deadlock conditions (mutual exclusion, hold and wait, no preemption, circular wait) and prevention.", resources: [{ title: "OS: Three Easy Pieces (free book)", url: "https://pages.cs.wisc.edu/~remzi/OSTEP/" }, { title: "MIT 6.004 — Computation Structures", url: "https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/" }] },
      { section: "Systems", order: 11, title: "Networking & TCP/IP Deep Dive", description: "Understand the network stack: OSI 7 layers (physical → data link → network → transport → session → presentation → application), IP addressing and subnetting, TCP 3-way handshake (SYN/SYN-ACK/ACK), TCP flow control (sliding window) and congestion control (slow start, AIMD), UDP trade-offs, and DNS resolution chain.", resources: [{ title: "Beej's Guide to Network Programming (free)", url: "https://beej.us/guide/bgnet/" }, { title: "High Performance Browser Networking (free book)", url: "https://hpbn.co" }] },
      { section: "Theory", order: 12, title: "Database Theory — ACID, Normalization & Indexes", description: "Understand database internals: ACID properties (Atomicity, Consistency, Isolation, Durability), isolation levels (Read Uncommitted, Read Committed, Repeatable Read, Serializable), B-tree and B+tree indexes (why pages matter), database normalization (1NF → 2NF → 3NF → BCNF), denormalization trade-offs, and WAL (Write-Ahead Logging).", resources: [{ title: "CMU 15-445 — Database Systems (free lectures)", url: "https://15445.courses.cs.cmu.edu/fall2022/" }, { title: "Use The Index, Luke! (free book)", url: "https://use-the-index-luke.com" }] },
      { section: "Theory", order: 13, title: "Compilers & Language Theory", description: "Understand how programming languages work: lexical analysis (tokenization), parsing (AST construction, LL/LR parsing), semantic analysis (type checking, scope), intermediate representations, code generation, and optimization passes. Understand regular expressions (DFA/NFA), context-free grammars (CFG), and the Chomsky hierarchy.", resources: [{ title: "Crafting Interpreters (free book)", url: "https://craftinginterpreters.com" }, { title: "Stanford Compilers Course (Coursera)", url: "https://www.coursera.org/learn/compilers" }] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // 150. REDIS & CACHING
  // ═══════════════════════════════════════════════════════════════
  {
    title: "Redis & Caching",
    description: "Master Redis — the world's most popular in-memory data store. From caching fundamentals and data structures to pub/sub, streams, Redis Cluster, and production patterns.",
    category: "Backend",
    icon: "Database",
    steps: [
      { section: "Caching Fundamentals", order: 1, title: "Caching Concepts & Why Redis", description: "Understand caching fundamentals: cache hits/misses, hit rate optimization, cache-aside (lazy loading), read-through, write-through, write-behind (write-back), and refresh-ahead patterns. Understand Redis's position: in-memory data store vs cache vs message broker vs session store, and when Redis beats Memcached.", resources: [{ title: "AWS — Caching Best Practices", url: "https://aws.amazon.com/caching/best-practices/" }, { title: "Redis Official Documentation", url: "https://redis.io/docs/" }] },
      { section: "Redis Basics", order: 2, title: "Getting Started — Installation & Redis CLI", description: "Set up Redis: install via Homebrew/apt/Docker (redis:alpine), use the Redis CLI (redis-cli), understand the CLIENT / SERVER model, basic commands (PING, SET, GET, DEL, EXISTS, KEYS, SCAN), the Redis configuration file (redis.conf), and using a managed Redis service (Upstash, Redis Cloud, Elasticache).", resources: [{ title: "Redis — Try Redis (interactive browser tutorial)", url: "https://try.redis.io" }, { title: "Redis — Quick Start", url: "https://redis.io/docs/getting-started/" }] },
      { section: "Data Structures", order: 3, title: "Redis Strings, Numbers & Expiry", description: "Master Redis Strings — the most versatile type: SET/GET/MSET/MGET, INCR/DECR/INCRBY for atomic counters, APPEND, GETRANGE, SETRANGE, TTL-based expiry (EXPIRE, EXPIREAT, PEXPIRE, TTL, PERSIST), EX/PX/NX/XX flags on SET, and using strings for storing JSON, binary data, and serialized objects.", resources: [{ title: "Redis — String Commands Reference", url: "https://redis.io/commands/?group=string" }, { title: "Redis University — RU101 (free course)", url: "https://university.redis.com/courses/ru101/" }] },
      { section: "Data Structures", order: 4, title: "Lists, Sets & Sorted Sets", description: "Use Redis collections: Lists (LPUSH/RPUSH, LPOP/RPOP, LRANGE, LLEN, BLPOP for blocking queues, message queues pattern), Sets (SADD/SMEMBERS/SISMEMBER, set operations: SUNION, SINTER, SDIFF for friend graphs and tag systems), and Sorted Sets (ZADD, ZRANGE, ZRANK, ZRANGEBYSCORE for leaderboards and rate limiting).", resources: [{ title: "Redis — Data Types Introduction", url: "https://redis.io/docs/data-types/" }, { title: "Redis University — RU101 Data Structures", url: "https://university.redis.com/courses/ru101/" }] },
      { section: "Data Structures", order: 5, title: "Hashes, HyperLogLog & Bitmaps", description: "Advanced Redis types: Hashes for storing objects (HSET, HGET, HMGET, HGETALL, HKEYS, HVALS, HINCRBY — e.g., user sessions), HyperLogLog for approximate unique counting at O(1) space (PFADD, PFCOUNT — e.g., DAU tracking), Bitmaps as space-efficient boolean arrays (SETBIT, GETBIT, BITCOUNT, BITPOS — e.g., daily active users per day).", resources: [{ title: "Redis — HyperLogLog", url: "https://redis.io/docs/data-types/probabilistic/hyperloglogs/" }, { title: "Redis — Bitmaps Guide", url: "https://redis.io/docs/data-types/bitmaps/" }] },
      { section: "Data Structures", order: 6, title: "Redis Streams for Event Sourcing", description: "Use Redis Streams as a lightweight message broker: XADD (append to stream with auto-generated IDs), XREAD (consume messages), XREADGROUP and XACK for consumer groups (at-least-once delivery), XPENDING for failed message tracking, stream trimming (MAXLEN), and comparing Streams to Kafka for simpler use cases.", resources: [{ title: "Redis — Streams Introduction", url: "https://redis.io/docs/data-types/streams-tutorial/" }, { title: "Redis Streams vs Kafka (comparison article)", url: "https://redis.com/blog/use-cases-for-redis-streams-vs-apache-kafka/" }] },
      { section: "Advanced Features", order: 7, title: "Pub/Sub for Real-Time Messaging", description: "Build real-time features with Redis Pub/Sub: PUBLISH, SUBSCRIBE, PSUBSCRIBE (pattern matching), UNSUBSCRIBE, and use cases (live notifications, chat rooms, event broadcasting). Understand trade-offs (no persistence, no acknowledgment, fire-and-forget) vs Streams for durability.", resources: [{ title: "Redis — Pub/Sub Documentation", url: "https://redis.io/docs/manual/pubsub/" }, { title: "Building a Chat with Redis Pub/Sub (tutorial)", url: "https://redis.io/learn/howtos/chatapp" }] },
      { section: "Advanced Features", order: 8, title: "Lua Scripting & Redis Transactions", description: "Ensure atomicity: Redis MULTI/EXEC transactions (all-or-nothing execution, WATCH for optimistic locking), DISCARD to cancel, and Lua scripting with EVAL (atomic script execution, KEYS and ARGV parameters, no context switching). Use scripts for complex atomic operations like check-and-set or rate limiting.", resources: [{ title: "Redis — Transactions Documentation", url: "https://redis.io/docs/manual/transactions/" }, { title: "Redis — Lua Scripting Guide", url: "https://redis.io/docs/manual/programmability/eval-intro/" }] },
      { section: "Production Patterns", order: 9, title: "Session Management & Rate Limiting", description: "Implement common Redis patterns: session store (SET session:{id} serialized_data EX ttl, sliding expiration), rate limiting with fixed window (INCR + EXPIRE), sliding window (ZRANGEBYSCORE + ZADD), and token bucket algorithms. JWT blacklisting for logout and distributed session sharing.", resources: [{ title: "Redis — Rate Limiting Pattern", url: "https://redis.io/learn/howtos/ratelimiting" }, { title: "express-rate-limit with ioredis (GitHub)", url: "https://github.com/express-rate-limit/rate-limit-redis" }] },
      { section: "Production Patterns", order: 10, title: "Distributed Locks & Leaderboards", description: "Build sophisticated patterns: distributed locks with SET key value NX PX ttl (atomic lock acquisition), Redlock algorithm for multi-instance lock safety, lock renewal with watchdog pattern. Leaderboards with Sorted Sets (ZADD scores, ZREVRANK for user rank, ZRANGE for top-N). Autocomplete with prefix matching using Sorted Sets.", resources: [{ title: "Redis — Distributed Locking (Redlock)", url: "https://redis.io/docs/manual/patterns/distributed-locks/" }, { title: "Redis — Leaderboard Pattern", url: "https://redis.io/learn/howtos/leaderboard" }] },
      { section: "HA & Scaling", order: 11, title: "Redis Persistence, Sentinel & Cluster", description: "Make Redis production-grade: persistence modes (RDB snapshots for backups, AOF for durability, RDB+AOF hybrid), Redis Sentinel for high availability (automatic failover, quorum-based master election, monitoring), and Redis Cluster for horizontal scaling (hash slots, data sharding across 16384 slots, cluster node communication).", resources: [{ title: "Redis — Persistence Documentation", url: "https://redis.io/docs/manual/persistence/" }, { title: "Redis Cluster Tutorial", url: "https://redis.io/docs/manual/scaling/" }] },
      { section: "Integration", order: 12, title: "Redis in Node.js, Python & Go", description: "Integrate Redis in popular stacks: Node.js with ioredis (connection pooling, pipelining, Cluster support) or redis npm package, Python with redis-py (connection pool, pipeline, async with aioredis), Go with go-redis/redis (typed commands, pipeline, hook middleware). Use redis:alpine in Docker Compose for local development.", resources: [{ title: "ioredis Documentation (Node.js)", url: "https://github.com/redis/ioredis" }, { title: "redis-py Documentation (Python)", url: "https://redis-py.readthedocs.io/en/stable/" }] },
    ],
  },
];

// ─── SEED FUNCTION ──────────────────────────────────────────────────────────

async function seedMoreRoadmaps() {
  console.log("🌱 Seeding 12 additional roadmaps (IDs 139–150)...\n");

  for (const [idx, roadmapData] of NEW_ROADMAPS.entries()) {
    const id = 139 + idx;
    console.log(`[${id}] ${roadmapData.title}`);

    // Upsert roadmap
    await db.insert(roadmaps).values({
      id,
      title: roadmapData.title,
      description: roadmapData.description,
      category: roadmapData.category,
      icon: roadmapData.icon,
      isPublished: true,
    }).onConflictDoUpdate({
      target: roadmaps.id,
      set: {
        title: roadmapData.title,
        description: roadmapData.description,
        category: roadmapData.category,
        icon: roadmapData.icon,
        isPublished: true,
      },
    });

    // Delete existing steps for this roadmap (clean re-seed)
    const { eq } = await import("drizzle-orm");
    await db.delete(roadmapSteps).where(eq(roadmapSteps.roadmapId, id));

    // Insert steps
    for (const step of roadmapData.steps) {
      await db.insert(roadmapSteps).values({
        roadmapId: id,
        section: step.section,
        order: step.order,
        title: step.title,
        description: step.description,
        resources: JSON.stringify(step.resources),
      });
    }

    console.log(`   ✓ ${roadmapData.steps.length} steps seeded`);
  }

  console.log(`\n✅ Done! ${NEW_ROADMAPS.length} roadmaps seeded (IDs 139–150).`);
  process.exit(0);
}

seedMoreRoadmaps().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
